### ISSUE TITLE
Move Add New Link button to the top

### ISSUE THREAD

**Issue by shay328** [maithemewp/mai-link-injector#1]
Can we please move the Add New Link button to the top of the link injector editor? 

Sites that have 500+ links requires a lot of scrolling and people miss where to add new links. 

 I'm open to having on at the top and bottom of the editor. 

I can't decide if the top button should go below the Limit field or before the table of links. 

![Annotation on 2023-05-04 at 11-39-18](https://user-images.githubusercontent.com/43424037/236258667-6b70d989-be3f-4b57-9afa-d30a93b795ef.png)

**Comment by JiveDig** [comment]
This is tricky. I can use CSS to move the button above the repeater, but when you click to add new, the new row is added to the bottom, and it doesn't jump you there automatically.

**Comment by JiveDig** [comment]
Repeater pagination would be great, but see here: https://twitter.com/JiveDig/status/1637871252508401671?s=20

I spent a while trying to get it to work and ultimately gave up. It may be possible but I'd have to put some time in to try it again. I'd love pagination to work.

<img width="597" alt="CleanShot 2023-05-04 at 13 14 30@2x" src="https://user-images.githubusercontent.com/540990/236277623-d45cba7a-54cd-43a2-9655-d6a122212654.png">

**Comment by JiveDig** [comment]
The simplest solution here is to use the + bottom at the top corner of the first item. Every row has those, so you can put one in wherever you want.

![CleanShot 2024-03-06 at 16 22 20@2x](https://github.com/maithemewp/mai-link-injector/assets/540990/8cf192b1-357e-49bb-b9a6-1182b65cb265)
