### ISSUE TITLE
count of links on a page doesn't appear to be working correctly

### ISSUE THREAD

**Issue by dws122** [maithemewp/mai-link-injector#3]
on TPS, at least two links are showing when Limit set to 1.

https://www.totalprosports.com/ncaa/texas-coach-steve-sarkisian-quinn-ewers-starting-over-arch-manning-reason/

![img_0861_720](https://github.com/maithemewp/mai-link-injector/assets/12969150/f35a9745-399d-4817-bfa7-ace6c82f0536)

<img width="857" alt="Screenshot 2024-03-01 at 6 49 36 PM" src="https://github.com/maithemewp/mai-link-injector/assets/12969150/1ee1abde-5fd1-46c8-b44c-39d7ecd179e8">

**Comment by JiveDig** [comment]
Interesting... the bug here is that I'm querying _nodes_, so that paragraph block is a single node, and links are applied for the entire node, not each instance of the text.

**Comment by JiveDig** [comment]
Got it.

**Comment by JiveDig** [comment]
This was finalized as only allowing the first instance of the keyword in a single element to be linked. So above example... NFL Draft would only be linked in the first instance inside that paragraph.
