### ISSUE TITLE
Consider counting all instances of the keywords on a page and spreading out the linked instances

### ISSUE THREAD

**Issue by JiveDig** [maithemewp/mai-link-injector#5]
If the linked text is "NFL" and our limit is 3, but there are 20 instance of "NFL" on the page, our current implementation links the first 3 instances and stops. It would be cool to spread out the links so the first, middle, and last instances are the linked ones.

I feel like Google may be smart enough to know the page is link loaded at the top? 

@dws122 Thoughts?

**Comment by dws122** [comment]
Interesting.  Should only be once per paragraph.  We could use syntax like in the CCA and indicate 1,5,9 to indicate after first find skip 5 paragraphs and after second find skip 9 more paragraphs.

**Comment by JiveDig** [comment]
I'm not referring to settings though, all automated. If there are only 3 instances, link all 3. If there are 12, link the 1st, 6th, and 12th. It would just be some math formula to separate them.

**Comment by JiveDig** [comment]
This is in now, but we can test and confirm we want it this way. In this screenshot, the limit is 4, but the links are not all in a row now.

<img width="584" alt="CleanShot 2024-03-08 at 12 49 32@2x" src="https://github.com/maithemewp/mai-link-injector/assets/540990/93bfe0f6-6487-4afa-9b11-8f4f4032bc1a">

**Comment by JiveDig** [comment]
Done in 1.4.0
