### ISSUE TITLE
Ignore links to the same/current page?

### ISSUE THREAD

**Issue by JiveDig** [maithemewp/mai-link-injector#6]
I think this is still happening. Assuming we shouldn't link to the same page, right?

**Comment by dws122** [comment]
I’d agree, ignore links to the same page.

**Comment by JiveDig** [comment]
Done via https://github.com/maithemewp/mai-link-injector/commit/fea3e4667d2c4e5eaa9cfbcf24ce7b987d3845ea in 1.4.0
